[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200
gas_reports = [
  "IPNFT",
  "IPNFTV2",
  "SchmackoSwap",
  "Tokenizer",
  "IPToken",
  "CrowdSale",
  "LockingCrowdSale",
  "StakedLockingCrowdSale",
  "TimelockedToken",
  "TermsAcceptedPermissioner",
  "SignedMintAuthorizer",
]
fs_permissions = [
  { access = "read-write", path = "./SALEID.txt" },
  { access = "read", path = "./out" },
]

[fmt]
bracket_spacing = true
line_length = 150
tab_width = 4
quote_style = 'double'
func_attrs_with_params_multiline = true
override_spacing = false
sort_imports = true

[rpc_endpoints]
optimism = "https://optimism-goerli.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
